import { contentHash } from "../models/model-audit";
import type { BenchmarkCandidateSelectionCatalogEntry } from "../benchmarks/action-compilation/retrievers/catalog";
import type { AlgorithmRef } from "./composition";
import type { WorldExecutionAlgorithmRegistry } from "../runtime/execution";

export interface AlgorithmRefDiff {
  path: string;
  field: "presence" | "identity" | "contractVersion" | "config";
  left: unknown;
  right: unknown;
}

export function flattenAlgorithmRef(ref: AlgorithmRef, path = "root"): Array<{ path: string; ref: AlgorithmRef }> {
  return [
    { path, ref },
    ...Object.entries(ref.children).flatMap(([slot, child]) => flattenAlgorithmRef(child, `${path}.${slot}`)),
  ];
}

export function diffAlgorithmRefs(left: AlgorithmRef, right: AlgorithmRef, path = "root"): AlgorithmRefDiff[] {
  if (left.manifestHash === right.manifestHash) return [];
  const differences: AlgorithmRefDiff[] = [];
  const leftIdentity = `${left.role}/${left.id}@${left.version}`;
  const rightIdentity = `${right.role}/${right.id}@${right.version}`;
  if (leftIdentity !== rightIdentity) differences.push({ path, field: "identity", left: leftIdentity, right: rightIdentity });
  if (left.contractVersion !== right.contractVersion) {
    differences.push({ path, field: "contractVersion", left: left.contractVersion, right: right.contractVersion });
  }
  if (contentHash(left.config) !== contentHash(right.config)) {
    differences.push({ path, field: "config", left: left.config, right: right.config });
  }
  const slots = [...new Set([...Object.keys(left.children), ...Object.keys(right.children)])].sort();
  for (const slot of slots) {
    const leftChild = left.children[slot];
    const rightChild = right.children[slot];
    if (!leftChild || !rightChild) {
      differences.push({
        path: `${path}.${slot}`,
        field: "presence",
        left: leftChild ? `${leftChild.role}/${leftChild.id}@${leftChild.version}` : null,
        right: rightChild ? `${rightChild.role}/${rightChild.id}@${rightChild.version}` : null,
      });
      continue;
    }
    differences.push(...diffAlgorithmRefs(leftChild, rightChild, `${path}.${slot}`));
  }
  return differences;
}

export function algorithmCatalogMarkdown(
  registry: WorldExecutionAlgorithmRegistry,
  defaultComposition: AlgorithmRef,
  benchmarkAlgorithms: readonly BenchmarkCandidateSelectionCatalogEntry[] = [],
): string {
  const definitions = registry.catalog();
  const lines = [
    "# Algorithm catalog",
    "",
    "<!-- Generated by `npm run algorithms -- catalog`; do not edit by hand. -->",
    "",
    "The executable registry is authoritative. Maturity describes enrollment policy and is not part of behavior identity.",
    "",
    "## Registered algorithms",
    "",
    "| Role | Algorithm | Contract | Maturity | Child slots |",
    "| --- | --- | ---: | --- | --- |",
    ...definitions.map((entry) => {
      const children = Object.entries(entry.childRoles).map(([slot, role]) => `\`${slot}\` → \`${role}\``).join("<br>") || "—";
      return `| \`${entry.role}\` | \`${entry.id}@${entry.version}\` | ${entry.contractVersion} | ${entry.maturity} | ${children} |`;
    }),
    "",
    "## Benchmark-only algorithms",
    "",
    "These implementations are replaceable inside the offline evaluation harness, but are not resolvable by an instance Composition. Promotion requires a registered production-batch implementation, pinned resources, and evidence accepted by the current activation gate.",
    "",
    "| Role | Algorithm | Family | Evaluation strategy | Contract | Maturity | Source | Evidence |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ...benchmarkAlgorithms.map((entry) => {
      const source = `../../${entry.source}`;
      const evidence = `../../${entry.evidence}`;
      return `| \`${entry.role}\` | \`${entry.id}@${entry.version}\` | ${entry.family} | \`${entry.strategy}\` | \`${entry.contract}\` | ${entry.maturity} | [implementation](${source}) | [evidence](${evidence}) |`;
    }),
    "",
    "## Default composition",
    "",
    `Root hash: \`${defaultComposition.manifestHash}\``,
    "",
    "| Node path | Role | Algorithm | Contract | Manifest hash |",
    "| --- | --- | --- | ---: | --- |",
    ...flattenAlgorithmRef(defaultComposition).map(({ path, ref }) =>
      `| \`${path}\` | \`${ref.role}\` | \`${ref.id}@${ref.version}\` | ${ref.contractVersion} | \`${ref.manifestHash}\` |`),
    "",
  ];
  return lines.join("\n");
}
